services:
  supotsu-backend:
    image: ghcr.io/supotsu-no-ochaya/supotsu-backend:dev
    container_name: supotsu-backend
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/app/pb_data
# only required if not downloading testdata
#    environment:
#      - PB_SUPERUSER_EMAIL=admin@admin.admin
#      - PB_SUPERUSER_PASSWORD=1234567890
